"""Add more menu db tables

Revision ID: 77ac46195828
Revises: 97cf0db26ae9
Create Date: 2025-07-14 21:10:28.688900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ac46195828'
down_revision = '97cf0db26ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('request_by')

    # ### end Alembic commands ###
