"""Add menu db table

Revision ID: 97cf0db26ae9
Revises: f32947559569
Create Date: 2025-07-14 21:05:49.516607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cf0db26ae9'
down_revision = 'f32947559569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('incident')
    op.drop_table('knowledge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('content', sa.VARCHAR(length=250), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=250), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('resolution_summary', sa.VARCHAR(length=250), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=250), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('resolution_summary', sa.VARCHAR(length=250), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
